# Generated by Django 5.1 on 2024-08-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_album_artist_alter_artist_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='album_photo/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='artist_pic/'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='playlist_photo/'),
        ),
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
