# Generated by Django 5.1 on 2024-08-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_remove_playlist_song_playlist_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='cover',
        ),
    ]
