# Generated by Django 5.1 on 2024-08-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_remove_song_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
