# Generated by Django 5.1 on 2024-08-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_song_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='songcover',
            field=models.ImageField(blank=True, null=True, upload_to='song_photo/'),
        ),
    ]
