# Generated by Django 5.1 on 2024-08-19 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_alter_profile_nickname_alter_profile_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='player.artist'),
        ),
    ]
