# Generated by Django 5.1 on 2024-08-22 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_playlist_public_alter_song_artist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
