# Generated by Django 5.1 on 2024-08-22 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_album_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='like',
            field=models.ManyToManyField(related_name='liked_albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
