# Generated by Django 5.1 on 2024-08-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_alter_album_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='player.song'),
        ),
    ]
