# Generated by Django 5.1 on 2024-08-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0016_alter_playlist_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='photo',
            field=models.ImageField(blank=True, default='default_playlist.png', null=True, upload_to='playlist_photo/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
