# Generated by Django 5.1 on 2024-08-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0017_alter_playlist_photo_alter_playlist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='photo',
            field=models.ImageField(blank=True, default='img/default-cover.png', null=True, upload_to='playlist_photo/'),
        ),
    ]
