# Generated by Django 5.1 on 2024-08-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0018_alter_playlist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='photo',
            field=models.ImageField(blank=True, default='default-cover.png', null=True, upload_to='playlist_photo/'),
        ),
    ]
