# Generated by Django 5.1 on 2024-08-30 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0021_artist_liked_alter_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='user_following', to='player.profile'),
        ),
        migrations.CreateModel(
            name='FollowingArtists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.artist')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_artists', to='player.profile')),
            ],
        ),
    ]
