# Generated by Django 5.1 on 2024-08-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0022_profile_following_followingartists'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_artists',
            field=models.ManyToManyField(blank=True, related_name='liked_by_profiles', to='player.artist'),
        ),
    ]
