# Generated by Django 5.1 on 2024-08-30 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0023_profile_liked_artists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='liked',
            new_name='liked_by',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='liked_artists',
        ),
    ]
