# Generated by Django 5.1 on 2024-08-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0024_rename_liked_artist_liked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_artists',
            field=models.ManyToManyField(blank=True, related_name='liked_artists', to='player.artist'),
        ),
    ]
