# Generated by Django 5.1 on 2024-08-30 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0025_profile_liked_artists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='liked_by',
            new_name='liked',
        ),
    ]
