# Generated by Django 5.1 on 2024-08-30 01:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0026_rename_liked_by_artist_liked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='like',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='liked_artists',
        ),
        migrations.AddField(
            model_name='album',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='followed_artists',
            field=models.ManyToManyField(blank=True, related_name='followed_artists', to='player.artist'),
        ),
        migrations.DeleteModel(
            name='FollowingArtists',
        ),
    ]
