# Generated by Django 5.1 on 2024-08-30 01:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0027_remove_album_like_remove_profile_liked_artists_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='liked',
        ),
        migrations.AddField(
            model_name='album',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artist',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
