# Generated by Django 5.1 on 2024-08-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0029_song_album_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_cover',
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_albums',
            field=models.ManyToManyField(blank=True, related_name='liked_albums', to='player.album'),
        ),
    ]
