# Generated by Django 5.1 on 2024-08-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0031_remove_album_like_remove_song_liked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked_songs',
            field=models.ManyToManyField(blank=True, related_name='liked_songs', to='player.song'),
        ),
    ]
