# Generated by Django 5.1.3 on 2024-11-16 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0034_remove_song_likes_artist_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='slug',
        ),
    ]
